### PR TITLE
Added support for Jump Options

### PR DESCRIPTION
**Pull request by andresmakesgames**
Yarn has support for Jump Options, format style:
[[Display text for user|NodeName]]
This enables support for this text feature.

### CODE REVIEW

**Review by cxsquared — APPROVED** [review]

**Comment by cxsquared** [comment]
@andresmakesgames thanks for the addition!

**Comment by andresmakesgames** [comment]
@cxsquared Thank you for getting it up and running! Happy to give back.

**Comment by cxsquared** [comment]
@andresmakesgames just want to let you know that I pushed up a fix for a bug that was introduced with this around markup/format function support.

**Comment by andresmakesgames** [comment]
I found the same bug last night and was going to submit a fix as well! Thank you!

**Pull request merged**
